---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true

---


##  Educational Experience

**Columbia University Mailman School of Public Health **

Master of Epidemiology

*September 2021-May 2023*

·Courses: Data Science I, Principle of Epidemiology I,
Introduction to Biostatistical Methods, Introduction to Health Economics

·Activities: CUMCCSSA




**Boston University College of Health and Rehabilitation Sciences & College of Art and Science**     

Bachelor of Health Science and Bachelor of Economics

*September 2016–May 2020*

·Activities and Honors: Dean’s List (4 semesters), National Honor Society, BUTFC, BUCSSA



##  Internship Experience

**Shanghai General Hospital**

Administration Assistant

*June 2019–August 2019*

·Managed 40+ doctors’ visa application processes for attending overseas conferences; ensured timely delivery of visa application forms and materials to meet Foreign Affairs offices’ requirements.

·Executed routine files, projects, and data entry using Excel and Word.

·Applied library and online research databases to conduct background research and a literature review on successful
hospital cases of transferring laboratory findings into useful clinical practices.

·Followed doctors and nurses during patients’ appointments. Helped 100+ patients in the outpatient department.


##  Skills

**Languages**: Native Mandarin, fluent English


**Software**: Microsoft Excel and PowerPoint, Python (dictionary, list comprehension, loop, finite-state machine,
 recursion, 2D-list), STATA, R



## Contact information

**Email**: gc2942@cumc.columbia.edu



### Click here for more complete one version...


**[Resume]** (https://issuu.com/gc2942/docs/resume）





